// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

/**
 * Protobuf enum {@code org.cook.rpc.sample.model.clock.DayOfWeek}
 */
public enum DayOfWeek
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUNDAY = 1;</code>
   */
  SUNDAY(1),
  /**
   * <code>MONDAY = 2;</code>
   */
  MONDAY(2),
  /**
   * <code>TUESDAY = 3;</code>
   */
  TUESDAY(3),
  /**
   * <code>WEDNESDAY = 4;</code>
   */
  WEDNESDAY(4),
  /**
   * <code>THURSDAY = 5;</code>
   */
  THURSDAY(5),
  /**
   * <code>FRIDAY = 6;</code>
   */
  FRIDAY(6),
  /**
   * <code>SATURDAY = 7;</code>
   */
  SATURDAY(7),
  ;

  /**
   * <code>SUNDAY = 1;</code>
   */
  public static final int SUNDAY_VALUE = 1;
  /**
   * <code>MONDAY = 2;</code>
   */
  public static final int MONDAY_VALUE = 2;
  /**
   * <code>TUESDAY = 3;</code>
   */
  public static final int TUESDAY_VALUE = 3;
  /**
   * <code>WEDNESDAY = 4;</code>
   */
  public static final int WEDNESDAY_VALUE = 4;
  /**
   * <code>THURSDAY = 5;</code>
   */
  public static final int THURSDAY_VALUE = 5;
  /**
   * <code>FRIDAY = 6;</code>
   */
  public static final int FRIDAY_VALUE = 6;
  /**
   * <code>SATURDAY = 7;</code>
   */
  public static final int SATURDAY_VALUE = 7;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DayOfWeek valueOf(int value) {
    return forNumber(value);
  }

  public static DayOfWeek forNumber(int value) {
    switch (value) {
      case 1: return SUNDAY;
      case 2: return MONDAY;
      case 3: return TUESDAY;
      case 4: return WEDNESDAY;
      case 5: return THURSDAY;
      case 6: return FRIDAY;
      case 7: return SATURDAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DayOfWeek> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>() {
          public DayOfWeek findValueByNumber(int number) {
            return DayOfWeek.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cook.rpc.sample.model.clock.WorldClockProtocol.getDescriptor().getEnumTypes().get(1);
  }

  private static final DayOfWeek[] VALUES = values();

  public static DayOfWeek valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DayOfWeek(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.cook.rpc.sample.model.clock.DayOfWeek)
}

