// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cook.rpc.sample.model.clock.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.cook.rpc.sample.model.clock.Continent continent = 1;</code>
   */
  boolean hasContinent();
  /**
   * <code>required .org.cook.rpc.sample.model.clock.Continent continent = 1;</code>
   */
  org.cook.rpc.sample.model.clock.Continent getContinent();

  /**
   * <code>required string city = 2;</code>
   */
  boolean hasCity();
  /**
   * <code>required string city = 2;</code>
   */
  java.lang.String getCity();
  /**
   * <code>required string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
