// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

public interface LocalTimesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cook.rpc.sample.model.clock.LocalTimes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.LocalTime localTime = 1;</code>
   */
  java.util.List<org.cook.rpc.sample.model.clock.LocalTime> 
      getLocalTimeList();
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.LocalTime localTime = 1;</code>
   */
  org.cook.rpc.sample.model.clock.LocalTime getLocalTime(int index);
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.LocalTime localTime = 1;</code>
   */
  int getLocalTimeCount();
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.LocalTime localTime = 1;</code>
   */
  java.util.List<? extends org.cook.rpc.sample.model.clock.LocalTimeOrBuilder> 
      getLocalTimeOrBuilderList();
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.LocalTime localTime = 1;</code>
   */
  org.cook.rpc.sample.model.clock.LocalTimeOrBuilder getLocalTimeOrBuilder(
      int index);
}
