// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

public interface LocationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cook.rpc.sample.model.clock.Locations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  java.util.List<org.cook.rpc.sample.model.clock.Location> 
      getLocationList();
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  org.cook.rpc.sample.model.clock.Location getLocation(int index);
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  int getLocationCount();
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  java.util.List<? extends org.cook.rpc.sample.model.clock.LocationOrBuilder> 
      getLocationOrBuilderList();
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  org.cook.rpc.sample.model.clock.LocationOrBuilder getLocationOrBuilder(
      int index);
}
