// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

/**
 * Protobuf type {@code org.cook.rpc.sample.model.clock.Locations}
 */
public  final class Locations extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.cook.rpc.sample.model.clock.Locations)
    LocationsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Locations.newBuilder() to construct.
  private Locations(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Locations() {
    location_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Locations(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              location_ = new java.util.ArrayList<org.cook.rpc.sample.model.clock.Location>();
              mutable_bitField0_ |= 0x00000001;
            }
            location_.add(
                input.readMessage(org.cook.rpc.sample.model.clock.Location.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        location_ = java.util.Collections.unmodifiableList(location_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cook.rpc.sample.model.clock.WorldClockProtocol.internal_static_org_cook_rpc_sample_model_clock_Locations_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cook.rpc.sample.model.clock.WorldClockProtocol.internal_static_org_cook_rpc_sample_model_clock_Locations_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cook.rpc.sample.model.clock.Locations.class, org.cook.rpc.sample.model.clock.Locations.Builder.class);
  }

  public static final int LOCATION_FIELD_NUMBER = 1;
  private java.util.List<org.cook.rpc.sample.model.clock.Location> location_;
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  public java.util.List<org.cook.rpc.sample.model.clock.Location> getLocationList() {
    return location_;
  }
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  public java.util.List<? extends org.cook.rpc.sample.model.clock.LocationOrBuilder> 
      getLocationOrBuilderList() {
    return location_;
  }
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  public int getLocationCount() {
    return location_.size();
  }
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  public org.cook.rpc.sample.model.clock.Location getLocation(int index) {
    return location_.get(index);
  }
  /**
   * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
   */
  public org.cook.rpc.sample.model.clock.LocationOrBuilder getLocationOrBuilder(
      int index) {
    return location_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getLocationCount(); i++) {
      if (!getLocation(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < location_.size(); i++) {
      output.writeMessage(1, location_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < location_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, location_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cook.rpc.sample.model.clock.Locations)) {
      return super.equals(obj);
    }
    org.cook.rpc.sample.model.clock.Locations other = (org.cook.rpc.sample.model.clock.Locations) obj;

    boolean result = true;
    result = result && getLocationList()
        .equals(other.getLocationList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLocationCount() > 0) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocationList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cook.rpc.sample.model.clock.Locations parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cook.rpc.sample.model.clock.Locations prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.cook.rpc.sample.model.clock.Locations}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.cook.rpc.sample.model.clock.Locations)
      org.cook.rpc.sample.model.clock.LocationsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cook.rpc.sample.model.clock.WorldClockProtocol.internal_static_org_cook_rpc_sample_model_clock_Locations_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cook.rpc.sample.model.clock.WorldClockProtocol.internal_static_org_cook_rpc_sample_model_clock_Locations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cook.rpc.sample.model.clock.Locations.class, org.cook.rpc.sample.model.clock.Locations.Builder.class);
    }

    // Construct using org.cook.rpc.sample.model.clock.Locations.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLocationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (locationBuilder_ == null) {
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        locationBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cook.rpc.sample.model.clock.WorldClockProtocol.internal_static_org_cook_rpc_sample_model_clock_Locations_descriptor;
    }

    @java.lang.Override
    public org.cook.rpc.sample.model.clock.Locations getDefaultInstanceForType() {
      return org.cook.rpc.sample.model.clock.Locations.getDefaultInstance();
    }

    @java.lang.Override
    public org.cook.rpc.sample.model.clock.Locations build() {
      org.cook.rpc.sample.model.clock.Locations result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cook.rpc.sample.model.clock.Locations buildPartial() {
      org.cook.rpc.sample.model.clock.Locations result = new org.cook.rpc.sample.model.clock.Locations(this);
      int from_bitField0_ = bitField0_;
      if (locationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = java.util.Collections.unmodifiableList(location_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cook.rpc.sample.model.clock.Locations) {
        return mergeFrom((org.cook.rpc.sample.model.clock.Locations)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cook.rpc.sample.model.clock.Locations other) {
      if (other == org.cook.rpc.sample.model.clock.Locations.getDefaultInstance()) return this;
      if (locationBuilder_ == null) {
        if (!other.location_.isEmpty()) {
          if (location_.isEmpty()) {
            location_ = other.location_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLocationIsMutable();
            location_.addAll(other.location_);
          }
          onChanged();
        }
      } else {
        if (!other.location_.isEmpty()) {
          if (locationBuilder_.isEmpty()) {
            locationBuilder_.dispose();
            locationBuilder_ = null;
            location_ = other.location_;
            bitField0_ = (bitField0_ & ~0x00000001);
            locationBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLocationFieldBuilder() : null;
          } else {
            locationBuilder_.addAllMessages(other.location_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getLocationCount(); i++) {
        if (!getLocation(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cook.rpc.sample.model.clock.Locations parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cook.rpc.sample.model.clock.Locations) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.cook.rpc.sample.model.clock.Location> location_ =
      java.util.Collections.emptyList();
    private void ensureLocationIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        location_ = new java.util.ArrayList<org.cook.rpc.sample.model.clock.Location>(location_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cook.rpc.sample.model.clock.Location, org.cook.rpc.sample.model.clock.Location.Builder, org.cook.rpc.sample.model.clock.LocationOrBuilder> locationBuilder_;

    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public java.util.List<org.cook.rpc.sample.model.clock.Location> getLocationList() {
      if (locationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(location_);
      } else {
        return locationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public int getLocationCount() {
      if (locationBuilder_ == null) {
        return location_.size();
      } else {
        return locationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public org.cook.rpc.sample.model.clock.Location getLocation(int index) {
      if (locationBuilder_ == null) {
        return location_.get(index);
      } else {
        return locationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder setLocation(
        int index, org.cook.rpc.sample.model.clock.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.set(index, value);
        onChanged();
      } else {
        locationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder setLocation(
        int index, org.cook.rpc.sample.model.clock.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        ensureLocationIsMutable();
        location_.set(index, builderForValue.build());
        onChanged();
      } else {
        locationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder addLocation(org.cook.rpc.sample.model.clock.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.add(value);
        onChanged();
      } else {
        locationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder addLocation(
        int index, org.cook.rpc.sample.model.clock.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.add(index, value);
        onChanged();
      } else {
        locationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder addLocation(
        org.cook.rpc.sample.model.clock.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        ensureLocationIsMutable();
        location_.add(builderForValue.build());
        onChanged();
      } else {
        locationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder addLocation(
        int index, org.cook.rpc.sample.model.clock.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        ensureLocationIsMutable();
        location_.add(index, builderForValue.build());
        onChanged();
      } else {
        locationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder addAllLocation(
        java.lang.Iterable<? extends org.cook.rpc.sample.model.clock.Location> values) {
      if (locationBuilder_ == null) {
        ensureLocationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, location_);
        onChanged();
      } else {
        locationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        locationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public Builder removeLocation(int index) {
      if (locationBuilder_ == null) {
        ensureLocationIsMutable();
        location_.remove(index);
        onChanged();
      } else {
        locationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public org.cook.rpc.sample.model.clock.Location.Builder getLocationBuilder(
        int index) {
      return getLocationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public org.cook.rpc.sample.model.clock.LocationOrBuilder getLocationOrBuilder(
        int index) {
      if (locationBuilder_ == null) {
        return location_.get(index);  } else {
        return locationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public java.util.List<? extends org.cook.rpc.sample.model.clock.LocationOrBuilder> 
         getLocationOrBuilderList() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(location_);
      }
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public org.cook.rpc.sample.model.clock.Location.Builder addLocationBuilder() {
      return getLocationFieldBuilder().addBuilder(
          org.cook.rpc.sample.model.clock.Location.getDefaultInstance());
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public org.cook.rpc.sample.model.clock.Location.Builder addLocationBuilder(
        int index) {
      return getLocationFieldBuilder().addBuilder(
          index, org.cook.rpc.sample.model.clock.Location.getDefaultInstance());
    }
    /**
     * <code>repeated .org.cook.rpc.sample.model.clock.Location location = 1;</code>
     */
    public java.util.List<org.cook.rpc.sample.model.clock.Location.Builder> 
         getLocationBuilderList() {
      return getLocationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cook.rpc.sample.model.clock.Location, org.cook.rpc.sample.model.clock.Location.Builder, org.cook.rpc.sample.model.clock.LocationOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cook.rpc.sample.model.clock.Location, org.cook.rpc.sample.model.clock.Location.Builder, org.cook.rpc.sample.model.clock.LocationOrBuilder>(
                location_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.cook.rpc.sample.model.clock.Locations)
  }

  // @@protoc_insertion_point(class_scope:org.cook.rpc.sample.model.clock.Locations)
  private static final org.cook.rpc.sample.model.clock.Locations DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cook.rpc.sample.model.clock.Locations();
  }

  public static org.cook.rpc.sample.model.clock.Locations getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Locations>
      PARSER = new com.google.protobuf.AbstractParser<Locations>() {
    @java.lang.Override
    public Locations parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Locations(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Locations> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Locations> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cook.rpc.sample.model.clock.Locations getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

