// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

public interface LocalTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cook.rpc.sample.model.clock.LocalTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 year = 1;</code>
   */
  boolean hasYear();
  /**
   * <code>required uint32 year = 1;</code>
   */
  int getYear();

  /**
   * <code>required uint32 month = 2;</code>
   */
  boolean hasMonth();
  /**
   * <code>required uint32 month = 2;</code>
   */
  int getMonth();

  /**
   * <code>required uint32 dayOfMonth = 4;</code>
   */
  boolean hasDayOfMonth();
  /**
   * <code>required uint32 dayOfMonth = 4;</code>
   */
  int getDayOfMonth();

  /**
   * <code>required .org.cook.rpc.sample.model.clock.DayOfWeek dayOfWeek = 5;</code>
   */
  boolean hasDayOfWeek();
  /**
   * <code>required .org.cook.rpc.sample.model.clock.DayOfWeek dayOfWeek = 5;</code>
   */
  org.cook.rpc.sample.model.clock.DayOfWeek getDayOfWeek();

  /**
   * <code>required uint32 hour = 6;</code>
   */
  boolean hasHour();
  /**
   * <code>required uint32 hour = 6;</code>
   */
  int getHour();

  /**
   * <code>required uint32 minute = 7;</code>
   */
  boolean hasMinute();
  /**
   * <code>required uint32 minute = 7;</code>
   */
  int getMinute();

  /**
   * <code>required uint32 second = 8;</code>
   */
  boolean hasSecond();
  /**
   * <code>required uint32 second = 8;</code>
   */
  int getSecond();
}
