// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldClockProtocol.proto

package org.cook.rpc.sample.model.clock;

public final class WorldClockProtocol {
  private WorldClockProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cook_rpc_sample_model_clock_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cook_rpc_sample_model_clock_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cook_rpc_sample_model_clock_Locations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cook_rpc_sample_model_clock_Locations_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cook_rpc_sample_model_clock_LocalTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cook_rpc_sample_model_clock_LocalTime_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cook_rpc_sample_model_clock_LocalTimes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cook_rpc_sample_model_clock_LocalTimes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030WorldClockProtocol.proto\022\037org.cook.rpc" +
      ".sample.model.clock\"W\n\010Location\022=\n\tconti" +
      "nent\030\001 \002(\0162*.org.cook.rpc.sample.model.c" +
      "lock.Continent\022\014\n\004city\030\002 \002(\t\"H\n\tLocation" +
      "s\022;\n\010location\030\001 \003(\0132).org.cook.rpc.sampl" +
      "e.model.clock.Location\"\251\001\n\tLocalTime\022\014\n\004" +
      "year\030\001 \002(\r\022\r\n\005month\030\002 \002(\r\022\022\n\ndayOfMonth\030" +
      "\004 \002(\r\022=\n\tdayOfWeek\030\005 \002(\0162*.org.cook.rpc." +
      "sample.model.clock.DayOfWeek\022\014\n\004hour\030\006 \002" +
      "(\r\022\016\n\006minute\030\007 \002(\r\022\016\n\006second\030\010 \002(\r\"K\n\nLo" +
      "calTimes\022=\n\tlocalTime\030\001 \003(\0132*.org.cook.r" +
      "pc.sample.model.clock.LocalTime*\231\001\n\tCont" +
      "inent\022\n\n\006AFRICA\020\000\022\013\n\007AMERICA\020\001\022\016\n\nANTARC" +
      "TICA\020\002\022\n\n\006ARCTIC\020\003\022\010\n\004ASIA\020\004\022\014\n\010ATLANTIC" +
      "\020\005\022\r\n\tAUSTRALIA\020\006\022\n\n\006EUROPE\020\007\022\n\n\006INDIAN\020" +
      "\010\022\013\n\007MIDEAST\020\t\022\013\n\007PACIFIC\020\n*g\n\tDayOfWeek" +
      "\022\n\n\006SUNDAY\020\001\022\n\n\006MONDAY\020\002\022\013\n\007TUESDAY\020\003\022\r\n" +
      "\tWEDNESDAY\020\004\022\014\n\010THURSDAY\020\005\022\n\n\006FRIDAY\020\006\022\014" +
      "\n\010SATURDAY\020\007B\004H\001P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_cook_rpc_sample_model_clock_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cook_rpc_sample_model_clock_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cook_rpc_sample_model_clock_Location_descriptor,
        new java.lang.String[] { "Continent", "City", });
    internal_static_org_cook_rpc_sample_model_clock_Locations_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_cook_rpc_sample_model_clock_Locations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cook_rpc_sample_model_clock_Locations_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_org_cook_rpc_sample_model_clock_LocalTime_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_cook_rpc_sample_model_clock_LocalTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cook_rpc_sample_model_clock_LocalTime_descriptor,
        new java.lang.String[] { "Year", "Month", "DayOfMonth", "DayOfWeek", "Hour", "Minute", "Second", });
    internal_static_org_cook_rpc_sample_model_clock_LocalTimes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_cook_rpc_sample_model_clock_LocalTimes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cook_rpc_sample_model_clock_LocalTimes_descriptor,
        new java.lang.String[] { "LocalTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
