// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/PBHeartbeatModel.proto

package org.cook.rpc.helix.model.protobuf;

public final class PBHeartbeatModelOuterClass {
  private PBHeartbeatModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cook_rpc_helix_model_protobuf_PBHeartbeatModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cook_rpc_helix_model_protobuf_PBHeartbeatModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/proto/PBHeartbeatModel.proto\022" +
      "!org.cook.rpc.helix.model.protobuf\" \n\020PB" +
      "HeartbeatModel\022\014\n\004beat\030\001 \001(\005B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_cook_rpc_helix_model_protobuf_PBHeartbeatModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cook_rpc_helix_model_protobuf_PBHeartbeatModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cook_rpc_helix_model_protobuf_PBHeartbeatModel_descriptor,
        new java.lang.String[] { "Beat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
