// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/PBHeartbeatModel.proto

package org.cook.rpc.helix.model.protobuf;

public interface PBHeartbeatModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cook.rpc.helix.model.protobuf.PBHeartbeatModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 beat = 1;</code>
   */
  int getBeat();
}
