// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/PBInputParameter.proto

package org.cook.rpc.helix.model.protobuf;

public interface PBInputParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cook.rpc.helix.model.protobuf.PBInputParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.Any parameters = 1;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getParametersList();
  /**
   * <code>repeated .google.protobuf.Any parameters = 1;</code>
   */
  com.google.protobuf.Any getParameters(int index);
  /**
   * <code>repeated .google.protobuf.Any parameters = 1;</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .google.protobuf.Any parameters = 1;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getParametersOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any parameters = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getParametersOrBuilder(
      int index);
}
